
# Here's the stuff to animate things in here
# just move them to main Makefile

polarbear.png: polarbear.pov
	$(MAKE) NAME=polarbear WD=48 HT=48 FRAMES=64 OPT=+KC anim

wbullet.png: wbullet.pov
	$(MAKE) NAME=wbullet WD=24 HT=24 FRAMES=64 anim
