#!/bin/bash

if [ -z $1 ]; then
echo "Usage: genspritelist.sh C_FILES"
echo "       Generates sprites_autogen.h and sprites_autogen.inc"
echo "       Run this script from the src/sprites directory!"
exit 1
fi

TYPES=`grep -h REGISTER_SPRITE_TYPE $*|cut -d '(' -f 2|cut -d ')' -f 1`

cat <<EOF > sprites_autogen.h~
#ifndef SPRITES_AUTOGEN_H
#define SPRITES_AUTOGEN_H
/* Warning! This file is automatically generated by 
   utils/genspritelist.sh. Do not edit! */

extern void sprite_types_register(void);
EOF
for t in $TYPES; do
echo "extern sprite_type_t $t;" >>  sprites_autogen.h~;
done
echo  >>  sprites_autogen.h~;
echo "#endif" >>  sprites_autogen.h~;

cat <<EOF > sprites_autogen.inc~
#include "sprite_types.h"
/* Warning! This file is automatically generated by 
   utils/genspritelist.sh. Do not edit! */

void sprite_types_register(void)
{
EOF

for t in $TYPES; do
echo "    obj_type_init(&($t.object_type));" >>  sprites_autogen.inc~;
echo "    dict_define(sprite_types,$t.object_type.name,&$t);" >>  sprites_autogen.inc~;
done
echo  "}" >>  sprites_autogen.inc~;

if [ -r sprites_autogen.inc ]; then
  if [ `md5sum sprites_autogen.inc|cut -d " " -f 1` != `md5sum sprites_autogen.inc~|cut -d " " -f 1` ]; then
  mv sprites_autogen.inc~ sprites_autogen.inc
  fi
else
  mv sprites_autogen.inc~ sprites_autogen.inc
fi

if [ -r sprites_autogen.h ]; then
    if [ `md5sum sprites_autogen.h|cut -d " " -f 1` != `md5sum sprites_autogen.h~|cut -d " " -f 1` ]; then
	mv sprites_autogen.h~ sprites_autogen.h
    fi
else
    mv sprites_autogen.h~ sprites_autogen.h
fi
