#ifndef SPRITES_AUTOGEN_H
#define SPRITES_AUTOGEN_H
/* Warning! This file is automatically generated by 
   utils/genspritelist.sh. Do not edit! */

extern void sprite_types_register(void);
extern sprite_type_t airballoon;
extern sprite_type_t asteroid;
extern sprite_type_t biplane;
extern sprite_type_t bird;
extern sprite_type_t bomb;
extern sprite_type_t bonusmachine;
extern sprite_type_t balloon;
extern sprite_type_t bonusring;
extern sprite_type_t bonus;
extern sprite_type_t bouncer;
extern sprite_type_t box;
extern sprite_type_t bullet;
extern sprite_type_t cannon;
extern sprite_type_t cannonball;
extern sprite_type_t cloud;
extern sprite_type_t draco;
extern sprite_type_t ldust;
extern sprite_type_t sdust;
extern sprite_type_t dsmoke;
extern sprite_type_t explosion;
extern sprite_type_t fire;
extern sprite_type_t fuel;
extern sprite_type_t hangar;
extern sprite_type_t hippo;
extern sprite_type_t mark;
extern sprite_type_t missile;
extern sprite_type_t pine;
extern sprite_type_t pingu;
extern sprite_type_t puff;
extern sprite_type_t blacksmoke;
extern sprite_type_t ufo;
extern sprite_type_t wave;
extern sprite_type_t zeppelin;

#endif
